# Form implementation generated from reading ui file 'app.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1003, 722)
        self.btn_download = QtWidgets.QPushButton(parent=Dialog)
        self.btn_download.setGeometry(QtCore.QRect(420, 300, 211, 71))
        self.btn_download.setObjectName("btn_download")
        self.label = QtWidgets.QLabel(parent=Dialog)
        self.label.setGeometry(QtCore.QRect(180, 230, 121, 31))
        self.label.setObjectName("label")
        self.link_video = QtWidgets.QLineEdit(parent=Dialog)
        self.link_video.setGeometry(QtCore.QRect(302, 230, 471, 41))
        self.link_video.setObjectName("link_video")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.btn_download.setText(_translate("Dialog", "Download"))
        self.label.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Download</span></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec())
