# Form implementation generated from reading ui file 'dangnhap.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from tkinter import Widget
from PyQt6 import QtCore, QtGui, QtWidgets
import sqlite3
path = "D:/hoc tap/python/data/qlgv.db"
conn = sqlite3.connect(path)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(647, 421)
        Dialog.setAutoFillBackground(False)
        Dialog.setStyleSheet("background-color: rgb(102, 255, 255);")
        self.label = QtWidgets.QLabel(parent=Dialog)
        self.label.setGeometry(QtCore.QRect(70, 90, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setTextInteractionFlags(QtCore.Qt.TextInteractionFlag.TextBrowserInteraction)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=Dialog)
        self.label_2.setGeometry(QtCore.QRect(70, 170, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.pushButton = QtWidgets.QPushButton(parent=Dialog)
        self.pushButton.setGeometry(QtCore.QRect(330, 270, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("background-color:rgb(218, 218, 218);")
        self.pushButton.setObjectName("pushButton")
        self.btn_exit = QtWidgets.QPushButton(parent=Dialog)
        self.btn_exit.setGeometry(QtCore.QRect(130, 270, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btn_exit.setFont(font)
        self.btn_exit.setStyleSheet("background-color:rgb(218, 218, 218);")
        self.btn_exit.setObjectName("btn_exit")
        self.txt_mk = QtWidgets.QLineEdit(parent=Dialog)
        self.txt_mk.setGeometry(QtCore.QRect(200, 170, 261, 41))
        self.txt_mk.setStyleSheet("background-color:rgb(218, 218, 218);")
        self.txt_mk.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.txt_mk.setObjectName("txt_mk")
        self.txt_tk = QtWidgets.QLineEdit(parent=Dialog)
        self.txt_tk.setGeometry(QtCore.QRect(200, 90, 261, 41))
        self.txt_tk.setStyleSheet("background-color:rgb(218, 218, 218);")
        self.txt_tk.setObjectName("txt_tk")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        self.pushButton.clicked.connect(self.login)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Đăng nhập"))
        Dialog.setToolTip(_translate("Dialog", "<html><head/><body><p><br/></p></body></html>"))
        self.label.setText(_translate("Dialog", "Tài khoản: "))
        self.label_2.setText(_translate("Dialog", "Mật khẩu: "))
        self.pushButton.setText(_translate("Dialog", "Đăng nhập"))
        self.btn_exit.setText(_translate("Dialog", "Thoát"))

    def login(self):
        tk = self.txt_tk.text()
        mk = self.txt_mk.text()
        
        cursor = conn.cursor()
        
        
        query = "SELECT * FROM Dang_nhap WHERE Ten_dang_nhap = ? AND Mat_khau = ?"
        cursor.execute(query, (tk, mk))
        result = cursor.fetchall()
        
        if tk == "admin" and mk == "admin":
            print("Đăng nhập thành công")
            widget.setCurrentIndex(1)
        elif result:
            print("Đăng nhập thành công")
        else:
            print("Đăng nhập thất bại")


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec())
